# Generated by Django 5.1.4 on 2026-02-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="arrears_history",
            field=models.TextField(
                blank=True, help_text="History of arrears/backlogs", null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="cgpa",
            field=models.CharField(
                blank=True, help_text="Candidate's CGPA", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="education_details",
            field=models.JSONField(
                blank=True, default=list, help_text="Education details from resume"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="experience_details",
            field=models.JSONField(
                blank=True, default=list, help_text="Experience details from resume"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="internships",
            field=models.TextField(
                blank=True, help_text="Internship experience details", null=True
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="skills_details",
            field=models.JSONField(
                blank=True, default=list, help_text="Skills details from resume"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="technical_skills",
            field=models.TextField(
                blank=True, help_text="Technical skills list", null=True
            ),
        ),
    ]
