# Generated by Django 4.2.7 on 2026-02-16 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True, null=True)),
                ("responsibilities", models.TextField(blank=True, null=True)),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("remote", "Remote"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                            ("lead", "Lead Level"),
                            ("executive", "Executive"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                ("required_skills", models.JSONField(blank=True, default=list)),
                ("preferred_skills", models.JSONField(blank=True, default=list)),
                ("skill_keywords", models.JSONField(blank=True, default=list)),
                ("feature_vector", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("application_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("external_url", models.URLField(blank=True, null=True)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="jobs.jobcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobSkillRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("required", "Required"),
                            ("preferred", "Preferred"),
                            ("bonus", "Bonus"),
                        ],
                        default="required",
                        max_length=20,
                    ),
                ),
                ("experience_years", models.IntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_requirements",
                        to="jobs.job",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.jobskill"
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "skill")},
            },
        ),
        migrations.CreateModel(
            name="JobMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_score", models.FloatField(default=0.0)),
                ("skills_match_score", models.FloatField(default=0.0)),
                ("experience_match_score", models.FloatField(default=0.0)),
                ("education_match_score", models.FloatField(default=0.0)),
                ("matched_skills", models.JSONField(blank=True, default=list)),
                ("missing_skills", models.JSONField(blank=True, default=list)),
                ("additional_skills", models.JSONField(blank=True, default=list)),
                ("match_reason", models.TextField(blank=True, null=True)),
                ("recommendation_rank", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_matches",
                        to="jobs.job",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_matches",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "ordering": ["-overall_score"],
                "indexes": [
                    models.Index(
                        fields=["resume", "overall_score"],
                        name="jobs_jobmat_resume__96fcdf_idx",
                    ),
                    models.Index(
                        fields=["job", "overall_score"],
                        name="jobs_jobmat_job_id_7564c3_idx",
                    ),
                ],
                "unique_together": {("resume", "job")},
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["title", "location"], name="jobs_job_title_0bda61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["required_skills"], name="jobs_job_require_800278_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_active"], name="jobs_job_is_acti_b6ae73_idx"
            ),
        ),
    ]
