# Generated by Django 4.2.7 on 2026-03-07 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resumes", "0003_add_matched_jobs"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="job",
            name="jobs_job_is_acti_b6ae73_idx",
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="idx_job_title_location",
            old_name="jobs_job_title_0bda61_idx",
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="idx_required_skills",
            old_name="jobs_job_require_800278_idx",
        ),
        migrations.RenameIndex(
            model_name="jobmatch",
            new_name="idx_resume_score",
            old_name="jobs_jobmat_resume__96fcdf_idx",
        ),
        migrations.RenameIndex(
            model_name="jobmatch",
            new_name="idx_job_score",
            old_name="jobs_jobmat_job_id_7564c3_idx",
        ),
        migrations.AlterUniqueTogether(
            name="jobmatch",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="job",
            name="company_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="complexity_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="job",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="last_matched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="match_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="match_threshold",
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="skill_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="skill_weights",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="click_through_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="confidence_level",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="conversion_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="is_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="is_saved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="is_viewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="location_match_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="recommendation_age_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="recommendation_source",
            field=models.CharField(
                choices=[
                    ("skill_match", "Skill Match"),
                    ("ml_model", "ML Model"),
                    ("collaborative", "Collaborative"),
                    ("content_based", "Content Based"),
                    ("hybrid", "Hybrid"),
                ],
                default="skill_match",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="salary_match_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="saved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="skill_match_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("entry", "Entry Level"),
                    ("mid", "Mid Level"),
                    ("senior", "Senior Level"),
                    ("lead", "Lead Level"),
                    ("executive", "Executive"),
                ],
                db_index=True,
                default="mid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                db_index=True,
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="jobmatch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="jobmatch",
            name="overall_score",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name="jobmatch",
            name="recommendation_rank",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name="jobmatch",
            unique_together={("resume", "job", "user")},
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["company", "is_active"], name="idx_company_active"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["job_type", "experience_level"], name="idx_job_type_exp"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_active", "created_at"], name="idx_active_created"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["skill_count", "match_threshold"], name="idx_skill_threshold"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["complexity_score"], name="idx_complexity"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["match_count"], name="idx_match_count"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["preferred_skills"], name="idx_preferred_skills"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["location", "job_type", "is_active"],
                name="idx_location_type_active",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["experience_level", "is_active"], name="idx_exp_level_active"
            ),
        ),
        migrations.AddIndex(
            model_name="jobmatch",
            index=models.Index(fields=["user", "overall_score"], name="idx_user_score"),
        ),
        migrations.AddIndex(
            model_name="jobmatch",
            index=models.Index(
                fields=["user", "is_viewed", "is_applied"], name="idx_user_interactions"
            ),
        ),
        migrations.AddIndex(
            model_name="jobmatch",
            index=models.Index(
                fields=["recommendation_source", "created_at"],
                name="idx_source_created",
            ),
        ),
        migrations.AddIndex(
            model_name="jobmatch",
            index=models.Index(
                fields=["overall_score", "created_at"], name="idx_score_created"
            ),
        ),
        migrations.AddIndex(
            model_name="jobmatch",
            index=models.Index(fields=["expires_at"], name="idx_expires"),
        ),
        migrations.AddIndex(
            model_name="jobmatch",
            index=models.Index(fields=["recommendation_age_days"], name="idx_rec_age"),
        ),
    ]
