# Generated by Django 4.2.7 on 2026-02-16 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="resumes/")),
                ("original_filename", models.CharField(max_length=255)),
                ("raw_text", models.TextField(blank=True, null=True)),
                ("processed_text", models.TextField(blank=True, null=True)),
                ("extracted_skills", models.JSONField(blank=True, default=list)),
                ("extracted_education", models.JSONField(blank=True, default=list)),
                ("extracted_experience", models.JSONField(blank=True, default=list)),
                ("extracted_contact_info", models.JSONField(blank=True, default=dict)),
                ("feature_vector", models.JSONField(blank=True, default=list)),
                ("skill_keywords", models.JSONField(blank=True, default=list)),
                ("file_size", models.IntegerField(default=0)),
                ("file_type", models.CharField(max_length=10)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills", models.JSONField(blank=True, default=dict)),
                ("total_skills_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completeness_score", models.FloatField(default=0.0)),
                ("skills_score", models.FloatField(default=0.0)),
                ("experience_score", models.FloatField(default=0.0)),
                ("education_score", models.FloatField(default=0.0)),
                ("overall_score", models.FloatField(default=0.0)),
                ("missing_skills", models.JSONField(blank=True, default=list)),
                ("improvement_suggestions", models.JSONField(blank=True, default=list)),
                ("skill_gaps", models.JSONField(blank=True, default=dict)),
                ("word_count", models.IntegerField(default=0)),
                ("sentence_count", models.IntegerField(default=0)),
                ("readability_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="resumes.resume",
                    ),
                ),
            ],
        ),
    ]
