# Generated by Django 4.2.7 on 2026-02-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_resume_job_match_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="matched_jobs",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
