# Generated by Django 4.2.7 on 2026-03-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0004_resume_extracted_achievements_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="extracted_achievements",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="extracted_certificates",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="extracted_projects",
        ),
        migrations.RemoveField(
            model_name="resumeanalysis",
            name="achievement_score",
        ),
        migrations.RemoveField(
            model_name="resumeanalysis",
            name="certification_score",
        ),
        migrations.RemoveField(
            model_name="resumeanalysis",
            name="projects_score",
        ),
        migrations.RemoveField(
            model_name="resumeanalysis",
            name="structure_score",
        ),
    ]
