# Generated by Django 4.2.7 on 2026-03-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0005_remove_resume_extracted_achievements_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="feedback",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
