# Generated by Django 4.2.7 on 2026-03-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0006_resumeanalysis_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resumeanalysis",
            name="improvement_suggestions",
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="basic_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="projects_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="structure_score",
            field=models.FloatField(default=0),
        ),
    ]
