# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('skill_extractor', 'Skill Extractor'), ('job_matcher', 'Job Matcher'), ('resume_analyzer', 'Resume Analyzer'), ('recommendation', 'Recommendation System')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('training_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deployed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SkillExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_skills', models.JSONField(default=list)),
                ('confidence_scores', models.JSONField(default=dict)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('model_version', models.CharField(max_length=50)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_extraction_results', to='resumes.resume')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0)),
                ('skills_score', models.FloatField(default=0.0)),
                ('experience_score', models.FloatField(default=0.0)),
                ('education_score', models.FloatField(default=0.0)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('skill_gap_analysis', models.JSONField(default=dict)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('algorithm_version', models.CharField(max_length=50)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('resume', 'job')},
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(max_length=20)),
                ('recommendations', models.JSONField(default=list)),
                ('user_interactions', models.JSONField(default=dict)),
                ('precision_at_k', models.FloatField(blank=True, null=True)),
                ('recall_at_k', models.FloatField(blank=True, null=True)),
                ('diversity_score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpskillingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('current_level', models.CharField(max_length=20)),
                ('target_level', models.CharField(max_length=20)),
                ('learning_resources', models.JSONField(default=list)),
                ('estimated_time_hours', models.IntegerField(default=0)),
                ('difficulty_level', models.CharField(default='intermediate', max_length=20)),
                ('priority_score', models.FloatField(default=0.0)),
                ('market_demand_score', models.FloatField(default=0.0)),
                ('salary_impact_score', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upskilling_suggestions', to='accounts.user')),
            ],
            options={
                'ordering': ['-priority_score'],
                'unique_together': {('user', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='ModelTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_data_size', models.IntegerField(default=0)),
                ('validation_data_size', models.IntegerField(default=0)),
                ('test_data_size', models.IntegerField(default=0)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('training_algorithm', models.CharField(max_length=100)),
                ('training_loss', models.FloatField(blank=True, null=True)),
                ('validation_loss', models.FloatField(blank=True, null=True)),
                ('training_time_minutes', models.IntegerField(default=0)),
                ('final_accuracy', models.FloatField(blank=True, null=True)),
                ('final_precision', models.FloatField(blank=True, null=True)),
                ('final_recall', models.FloatField(blank=True, null=True)),
                ('final_f1_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to='ml_engine.mlmodel')),
            ],
        ),
    ]
