# Generated by Django 4.2.7 on 2026-03-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("candidate", "Candidate"),
                    ("hr", "HR/Recruiter"),
                    ("admin", "Admin"),
                ],
                default="candidate",
                max_length=20,
            ),
        ),
    ]
